### ISSUE TITLE
What is the minimum environment requirement?

### ISSUE THREAD

**Issue by caspervonb** [matthewmueller/joy#62]
> Outputs ES3 Javascript that works in every browser
That's all fine and well, but it's inconsistent, async is used for one.

But also comments like the following from stdlib/json

> // TODO: create & use object.assign runtime

So, do we prefer idiomatic JavaScript, or what's most widely available?

In other words, choose  `String.prototype.indexOf` over `String.prototype.includes` for implementing `strings.Contains`?

**Comment by matthewmueller** [comment]
That comment was confusing – I meant an object assign equivalent (pretty much just a for loop). 

Right now Joy compiles to ES7, but I have a path to ES3 that I think will work. 

There's actually only 2 things that aren't ES3 compatible right now:

- async/await: ideally we'll replace with generators and then use regenerator to compiler to ES3.
- function.prototype.bind: this will just be a function wrapper inside the runtime, whenever it's needed
