### ISSUE TITLE
Missing standard library packages

### ISSUE THREAD

**Issue by stern0** [matthewmueller/joy#76]
It seems that certain standard library packages are not supported, in this very case `context` and `sync` as I had the following error.

`could not import context (the 'context' package is not supported in joy yet)`
and
`could not import sync (the 'sync' package is not supported in joy yet)`

**Comment by caspervonb** [comment]
Most are not implemented at this time, take a look at the stdlib folder to see what's there.

**Comment by stern0** [comment]
Thanks @caspervonb, I will. closing now.
