### ISSUE TITLE
[Question] Installation on windows

### ISSUE THREAD

**Issue by ericmdantas** [matthewmueller/joy#90]
Hey there! Awesome project and concept.

I was wondering if there's a way to install `joy` on windows? I couldn't do it through `go get` or anything similar.

**Comment by tryy3** [comment]
Windows currently have some issues, it's not hard to install but when running you will need to keep a few things in mind.

So to install it easiest way is to run this commands:
`go get github.com/matthewmueller/joy`
`go get github.com/matthewmueller/joy/cmd/joy`

The problem with windows is that it has a "window controller" program, for game controllers, joysticks etc.
Which happens to be called "joy" so even once you have installed joy, it wont run when you try to run the command "joy".

The easiest solution is probably to just rename the binary file to something like joyc in your $GOPATH/bin folder.

**Comment by ericmdantas** [comment]
Thanks, @tryy3!
